{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-data-redis",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "io.lettuce",
          "module": "lettuce-core",
          "version": {
            "requires": "6.3.0.RELEASE"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-redis",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-redis-3.2.1.jar",
          "url": "spring-boot-starter-data-redis-3.2.1.jar",
          "size": 4783,
          "sha512": "a39e50644623c7284159e03adc00afe4e11a63102cfc02a106720b641e9b4d6caf77dc12db31413cebf02f0eea6ffc443fef50c487a0848f1a6f5bd457d06b98",
          "sha256": "06906a27a0b9312825b932f869837c5055bc36ae6cb671b2613498111d0b11b9",
          "sha1": "09b162003e51a62075cf2dc84932e0b1c77149e1",
          "md5": "02e02b0315e708067eebff3657175017"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "io.lettuce",
          "module": "lettuce-core",
          "version": {
            "requires": "6.3.0.RELEASE"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-redis",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-redis-3.2.1.jar",
          "url": "spring-boot-starter-data-redis-3.2.1.jar",
          "size": 4783,
          "sha512": "a39e50644623c7284159e03adc00afe4e11a63102cfc02a106720b641e9b4d6caf77dc12db31413cebf02f0eea6ffc443fef50c487a0848f1a6f5bd457d06b98",
          "sha256": "06906a27a0b9312825b932f869837c5055bc36ae6cb671b2613498111d0b11b9",
          "sha1": "09b162003e51a62075cf2dc84932e0b1c77149e1",
          "md5": "02e02b0315e708067eebff3657175017"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-redis-3.2.1.jar",
          "url": "spring-boot-starter-data-redis-3.2.1.jar",
          "size": 4783,
          "sha512": "a39e50644623c7284159e03adc00afe4e11a63102cfc02a106720b641e9b4d6caf77dc12db31413cebf02f0eea6ffc443fef50c487a0848f1a6f5bd457d06b98",
          "sha256": "06906a27a0b9312825b932f869837c5055bc36ae6cb671b2613498111d0b11b9",
          "sha1": "09b162003e51a62075cf2dc84932e0b1c77149e1",
          "md5": "02e02b0315e708067eebff3657175017"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-data-redis-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-redis-3.2.1.jar",
          "url": "spring-boot-starter-data-redis-3.2.1.jar",
          "size": 4783,
          "sha512": "a39e50644623c7284159e03adc00afe4e11a63102cfc02a106720b641e9b4d6caf77dc12db31413cebf02f0eea6ffc443fef50c487a0848f1a6f5bd457d06b98",
          "sha256": "06906a27a0b9312825b932f869837c5055bc36ae6cb671b2613498111d0b11b9",
          "sha1": "09b162003e51a62075cf2dc84932e0b1c77149e1",
          "md5": "02e02b0315e708067eebff3657175017"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-data-redis-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-redis-3.2.1-javadoc.jar",
          "url": "spring-boot-starter-data-redis-3.2.1-javadoc.jar",
          "size": 4747,
          "sha512": "081ba1bd06527557fb1447e715d91a7c11b157b403ba50c598794365feac4356587a1aef9d5c9cbd98610e479d614b8d19c9a479c2107850fed38d7f02c03480",
          "sha256": "ce02a07f90ab762ea7aa7fe6feeb99df5af76eea47e5ccc5763f0fa09d01c051",
          "sha1": "b624570eed8a9a07ab43083084e13956e18b2004",
          "md5": "ae0f1bde2739b98a0c78de3db391a13d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-redis-3.2.1-sources.jar",
          "url": "spring-boot-starter-data-redis-3.2.1-sources.jar",
          "size": 4745,
          "sha512": "6c64b08bae9c428ed393d0ad289d50c680aa0063cce8aec7886405964a76db1cb324aa05ee75f35e6a5bb28e7c65dc2b1bba4480b4151cfb73be4cb690b7d901",
          "sha256": "eeb92859c94abdbc2b4ab282d4057144ee6ecbb7ffd20ecc3ee7fef0ae01d43b",
          "sha1": "6cc5271221f845414f9ee66d877ecb2c4c64d261",
          "md5": "0709c02a2c97f00f5d0b71201be42f81"
        }
      ]
    }
  ]
}
