{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-oxm",
    "version": "6.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-oxm-6.1.2.jar",
          "url": "spring-oxm-6.1.2.jar",
          "size": 59804,
          "sha512": "8b1af46e5f6ca946546139880f70ea08b606f966dfce1acb0375fbce76ee964779580694d67ca10fd708c5958053077a8fbd46fbd1dc6f2aecdc4f0242725670",
          "sha256": "ef8d0dd12ede906e192722b290368c590b746a88f359ae1fb733c4d4b4c6acf2",
          "sha1": "7b90a221115d9b9668b40597d2328f3633f1c804",
          "md5": "a30793d8dc58c8bb644e3f478dc1ce57"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-oxm-6.1.2.jar",
          "url": "spring-oxm-6.1.2.jar",
          "size": 59804,
          "sha512": "8b1af46e5f6ca946546139880f70ea08b606f966dfce1acb0375fbce76ee964779580694d67ca10fd708c5958053077a8fbd46fbd1dc6f2aecdc4f0242725670",
          "sha256": "ef8d0dd12ede906e192722b290368c590b746a88f359ae1fb733c4d4b4c6acf2",
          "sha1": "7b90a221115d9b9668b40597d2328f3633f1c804",
          "md5": "a30793d8dc58c8bb644e3f478dc1ce57"
        }
      ]
    }
  ]
}
