{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-context-support",
    "version": "6.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-support-6.1.2.jar",
          "url": "spring-context-support-6.1.2.jar",
          "size": 174054,
          "sha512": "20569cbc039f065c098a748735cf7910d0136a4d87ddf70fe282916f54ea7aba5af89e6d6e59cb1475b3ac57bafcbcb67a6c163251de23e6f4f2f9e4726617c4",
          "sha256": "c678304f4fb6501165383f477d78f1db7642a08156b13d9c83b9d17d67d0efd1",
          "sha1": "ca7a86d2b96b0faa2674d98eb91875bd634390b2",
          "md5": "cd4cf1acd32b88f91fe8b64f758aec6d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-support-6.1.2.jar",
          "url": "spring-context-support-6.1.2.jar",
          "size": 174054,
          "sha512": "20569cbc039f065c098a748735cf7910d0136a4d87ddf70fe282916f54ea7aba5af89e6d6e59cb1475b3ac57bafcbcb67a6c163251de23e6f4f2f9e4726617c4",
          "sha256": "c678304f4fb6501165383f477d78f1db7642a08156b13d9c83b9d17d67d0efd1",
          "sha1": "ca7a86d2b96b0faa2674d98eb91875bd634390b2",
          "md5": "cd4cf1acd32b88f91fe8b64f758aec6d"
        }
      ]
    }
  ]
}
