{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sentry",
    "module": "sentry-logback",
    "version": "8.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.sentry",
          "module": "sentry",
          "version": {
            "requires": "8.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sentry-logback-8.1.0.jar",
          "url": "sentry-logback-8.1.0.jar",
          "size": 6731,
          "sha512": "d062b5c5522adc79a3a6fa3ec471208bd88a415a27e6232a08d43496dacdc47c710997aff685e8054a94a07591d97a29934e2c91cbffc044d284f24a9bb7d516",
          "sha256": "01f1cf4ede400b2f960fda577752bad9f79e72501cc65cd9c8bd5327a8481976",
          "sha1": "3d0b46ded61a9f7b9f34216afaaad0b869956ae4",
          "md5": "ceeb83c8cabefb316a19d83cabafe532"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.sentry",
          "module": "sentry",
          "version": {
            "requires": "8.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sentry-logback-8.1.0.jar",
          "url": "sentry-logback-8.1.0.jar",
          "size": 6731,
          "sha512": "d062b5c5522adc79a3a6fa3ec471208bd88a415a27e6232a08d43496dacdc47c710997aff685e8054a94a07591d97a29934e2c91cbffc044d284f24a9bb7d516",
          "sha256": "01f1cf4ede400b2f960fda577752bad9f79e72501cc65cd9c8bd5327a8481976",
          "sha1": "3d0b46ded61a9f7b9f34216afaaad0b869956ae4",
          "md5": "ceeb83c8cabefb316a19d83cabafe532"
        }
      ]
    }
  ]
}
