-- =====================================================================
-- 429 브랜치 배포용 마이그레이션   (MySQL 8 / inu_portal, inu_portal_dev)
--
-- [범위]
--   (A) Department enum 확장  : Java Department 가 92개 값이 됨(신규 7 + 코드없는 연계 1 + UNKNOWN).
--                                MySQL 네이티브 ENUM 컬럼 7개를 이 목록으로 MODIFY.
--   (B) College enum 재정의    : Java College 에서 HUSS 제거 + UNKNOWN 등 추가(총 21).
--                                course.college 를 MODIFY. 사전에 college='HUSS' 행을 ETC 로 이전.
--   (C) course_offering enum 컬럼 8개 DROP.
--   (D) prod 누락 인덱스 3개 생성 (dev 는 이미 있으므로 실행하면 1061 에러 → prod 에서만).
--   (E) course_offering 과거(엑셀) 행의 *_code 백필.
--
-- [전제]
--   - 새 코드가 로컬 JDK 17 로 ./gradlew clean build 통과.
--   - ddl-auto=update 는 ENUM 값 목록 변경/컬럼 DROP 을 확실히 처리하지 않으므로 명시적으로 수행.
--
-- [실행 순서]
--   PHASE 1 (배포 창, 트래픽 차단 상태 권장)
--     1-1  course.college : HUSS -> ETC        (B 사전작업)
--     1-2  Department ENUM 컬럼 7개 MODIFY      (A)   ※ dev/prod 공통
--     1-3  course.college ENUM MODIFY          (B)
--     1-4  course_offering DROP COLUMN x8      (C)
--     1-5  [prod 만] 인덱스 3개 CREATE          (D)
--     -> 새 코드 배포 / 기동
--   PHASE 2 (배포 후 아무 때나, 멱등)
--     2-1..2-8  *_code 백필 (college/hy/isu/english/cnctr_isu/isu_fld/ssup_type/dept)   (E)
--   PHASE 3
--     검증 SELECT
--
-- [주의]
--   - course.department / member.department 등은 모두 동일한 Java Department enum 사용 →
--     7개 컬럼 전부 같은 92개 값 목록으로 통일한다. (Hibernate 재기동 시 재-ALTER 방지 목적 포함)
--   - course.department, prod course_offering.dept_name 등 기존 값은 새 92개의 부분집합이라
--     MODIFY 시 데이터 손실 없음. college 의 HUSS 만 예외 → 1-1 로 선처리.
--   - MySQL 8 은 CREATE INDEX IF NOT EXISTS 미지원. 1-5 는 prod 에서만.
--   - '소비자ㆍ아동학과' 의 'ㆍ' 는 U+318D. 2-8 백필 후 그 값이 안 줄면
--     SELECT DISTINCT HEX(dept_name_raw) 로 실제 저장 문자 확인 후 조정.
--   - dept_code NULL 로 남는 값(정상): 국제개발협력연계전공(enum 코드 없음), 뷰티산업연계전공,
--     MICE,스포츠및관광연계전공, 인공지능·창업연계전공, 인공지능소프트웨어연계전공, dept_name_raw IS NULL
--   - isu_code NULL 로 남는 값(정상): 편람 옛 이수구분(전공필수/전공선택/공통필수/교양필수 등)
--
-- [옛 학과명 -> 현행 코드 매핑 근거]
--   메카트로닉스공학과 -> 0000814(2024 개편, 바이오-로봇시스템공학과) / 한국통상전공 -> 0000832(IBE)
--   체육학부 -> 0000815(스포츠과학부) / 동북아국제통상학부·동북아통상전공 -> 0000817
--   건설환경공학부 -> 0000156 / 신문방송학과 -> 0000794 / 일어일문학과 -> 0000793
--   나노바이오전공 -> 0000833 / 지능로봇연계전공 -> 0000912 / 소비자ㆍ아동학과 -> 0000704
--   XXX(야) -> 해당 주간 학과 코드
--
-- [무중단(롤링)이 필요하면]
--   1-4 DROP COLUMN 은 구 코드가 값을 쓰므로 반드시 다운타임 필요.
--   대안: (a) 배포 전 8개 컬럼 MODIFY ... NULL  (b) 전 인스턴스 롤아웃 후 DROP COLUMN.
--   1-2/1-5 는 온라인 DDL(ALGORITHM=INPLACE) 로 트래픽 중 실행 가능.
--   1-1/1-3 은 HUSS 를 쓰는 구 코드 경로가 있으면 다운타임 권장.
-- =====================================================================


-- ===================== PHASE 1 =====================

-- 1-1
UPDATE course SET college = 'ETC' WHERE college = 'HUSS';

-- 1-2  Department ENUM 컬럼 7개  (dev/prod 공통)
ALTER TABLE course MODIFY COLUMN department
    ENUM('KOREAN','ENGLISH','GERMAN','FRENCH','JAPANESE','CHINESE','MATHEMATICS','PHYSICS','CHEMISTRY','FASHION','MARINE','SOCIAL_WELFARE','MEDIA_COMMUNICATION','LIBRARY_INFO','CREATIVE_HRD','PUBLIC_ADMINISTRATION','POLITICS_DIPLOMACY','ECONOMICS','TRADE','CONSUMER_SCIENCE','ENERGY_CHEMICAL','ELECTRICAL_ENGINEERING','ELECTRONICS_ENGINEERING','INDUSTRIAL_MANAGEMENT','MATERIAL_SCIENCE','MECHANICAL_ENGINEERING','BIO_ROBOTICS_ENGINEERING','SAFETY_ENGINEERING','COMPUTER_ENGINEERING','INFORMATION_COMMUNICATION_ENGINEERING','EMBEDDED_SYSTEM','BUSINESS_ADMINISTRATION','DATA_SCIENCE','TAX_ACCOUNTING','TECHNO_MANAGEMENT','FINE_ARTS','KOREAN_PAINTING','WESTERN_PAINTING','DESIGN','PERFORMING_ART','SPORTS_SCIENCE','HEALTH_EXERCISE','KOREAN_EDUCATION','ENGLISH_EDUCATION','JAPANESE_EDUCATION','MATH_EDUCATION','PHYSICAL_EDUCATION','EARLY_CHILDHOOD_EDUCATION','HISTORY_EDUCATION','ETHICS_EDUCATION','URBAN_ADMINISTRATION','CIVIL_ENVIRONMENT_ENGINEERING','ENVIRONMENT_ENGINEERING','URBAN_ENGINEERING','URBAN_ARCHITECTURE','URBAN_ARCHITECTURE_ENGINEERING','URBAN_ARCHITECTURE_ARCHITECTURE','LIFE_SCIENCE','LIFE_SCIENCE_MOLECULAR','BIOENGINEERING','BIOENGINEERING_NANO','LIBERAL_ARTS','INTERNATIONAL_LIBERAL_ARTS','CONVERGENCE','NORTHEAST_ASIAN_TRADE','SMART_LOGISTICS_ENGINEERING','IBE','LAW','GENERAL','GENERAL_ELECTIVE','TEACHING','MILITARY_SCIENCE','HUSS_OTHER_UNIVERSITY','HUSS_INCLUSIVE_SOCIAL_INITIATIVE','OPTICAL_ELECTRONICS_LINKED','LOGISTICS_LINKED','FUTURE_EDUCATION_DESIGN_LINKED','FUTURE_CAR_LINKED','SEMICONDUCTOR_CONVERGENCE','SOCIAL_DATA_SCIENCE_LINKED','HUMANITIES_CULTURE_ART_PLANNING_LINKED','INTELLIGENT_ROBOT_SYSTEM_LINKED','CREATIVE_DESIGN_LINKED','INTERNATIONAL_DEVELOPMENT_COOPERATION_LINKED','ECONOMICS_EVENING','TRADE_EVENING','ELECTRONICS_ENGINEERING_DEPARTMENT','ELECTRONICS_ENGINEERING_MAJOR','URBAN_ENVIRONMENT_DIVISION','LIFE_SCIENCE_DIVISION','BIOENGINEERING_DIVISION','UNKNOWN')
    COLLATE utf8mb4_general_ci NOT NULL;

ALTER TABLE department_notice MODIFY COLUMN department
    ENUM('KOREAN','ENGLISH','GERMAN','FRENCH','JAPANESE','CHINESE','MATHEMATICS','PHYSICS','CHEMISTRY','FASHION','MARINE','SOCIAL_WELFARE','MEDIA_COMMUNICATION','LIBRARY_INFO','CREATIVE_HRD','PUBLIC_ADMINISTRATION','POLITICS_DIPLOMACY','ECONOMICS','TRADE','CONSUMER_SCIENCE','ENERGY_CHEMICAL','ELECTRICAL_ENGINEERING','ELECTRONICS_ENGINEERING','INDUSTRIAL_MANAGEMENT','MATERIAL_SCIENCE','MECHANICAL_ENGINEERING','BIO_ROBOTICS_ENGINEERING','SAFETY_ENGINEERING','COMPUTER_ENGINEERING','INFORMATION_COMMUNICATION_ENGINEERING','EMBEDDED_SYSTEM','BUSINESS_ADMINISTRATION','DATA_SCIENCE','TAX_ACCOUNTING','TECHNO_MANAGEMENT','FINE_ARTS','KOREAN_PAINTING','WESTERN_PAINTING','DESIGN','PERFORMING_ART','SPORTS_SCIENCE','HEALTH_EXERCISE','KOREAN_EDUCATION','ENGLISH_EDUCATION','JAPANESE_EDUCATION','MATH_EDUCATION','PHYSICAL_EDUCATION','EARLY_CHILDHOOD_EDUCATION','HISTORY_EDUCATION','ETHICS_EDUCATION','URBAN_ADMINISTRATION','CIVIL_ENVIRONMENT_ENGINEERING','ENVIRONMENT_ENGINEERING','URBAN_ENGINEERING','URBAN_ARCHITECTURE','URBAN_ARCHITECTURE_ENGINEERING','URBAN_ARCHITECTURE_ARCHITECTURE','LIFE_SCIENCE','LIFE_SCIENCE_MOLECULAR','BIOENGINEERING','BIOENGINEERING_NANO','LIBERAL_ARTS','INTERNATIONAL_LIBERAL_ARTS','CONVERGENCE','NORTHEAST_ASIAN_TRADE','SMART_LOGISTICS_ENGINEERING','IBE','LAW','GENERAL','GENERAL_ELECTIVE','TEACHING','MILITARY_SCIENCE','HUSS_OTHER_UNIVERSITY','HUSS_INCLUSIVE_SOCIAL_INITIATIVE','OPTICAL_ELECTRONICS_LINKED','LOGISTICS_LINKED','FUTURE_EDUCATION_DESIGN_LINKED','FUTURE_CAR_LINKED','SEMICONDUCTOR_CONVERGENCE','SOCIAL_DATA_SCIENCE_LINKED','HUMANITIES_CULTURE_ART_PLANNING_LINKED','INTELLIGENT_ROBOT_SYSTEM_LINKED','CREATIVE_DESIGN_LINKED','INTERNATIONAL_DEVELOPMENT_COOPERATION_LINKED','ECONOMICS_EVENING','TRADE_EVENING','ELECTRONICS_ENGINEERING_DEPARTMENT','ELECTRONICS_ENGINEERING_MAJOR','URBAN_ENVIRONMENT_DIVISION','LIFE_SCIENCE_DIVISION','BIOENGINEERING_DIVISION','UNKNOWN')
    COLLATE utf8mb4_general_ci NOT NULL;

ALTER TABLE fcm_message MODIFY COLUMN department
    ENUM('KOREAN','ENGLISH','GERMAN','FRENCH','JAPANESE','CHINESE','MATHEMATICS','PHYSICS','CHEMISTRY','FASHION','MARINE','SOCIAL_WELFARE','MEDIA_COMMUNICATION','LIBRARY_INFO','CREATIVE_HRD','PUBLIC_ADMINISTRATION','POLITICS_DIPLOMACY','ECONOMICS','TRADE','CONSUMER_SCIENCE','ENERGY_CHEMICAL','ELECTRICAL_ENGINEERING','ELECTRONICS_ENGINEERING','INDUSTRIAL_MANAGEMENT','MATERIAL_SCIENCE','MECHANICAL_ENGINEERING','BIO_ROBOTICS_ENGINEERING','SAFETY_ENGINEERING','COMPUTER_ENGINEERING','INFORMATION_COMMUNICATION_ENGINEERING','EMBEDDED_SYSTEM','BUSINESS_ADMINISTRATION','DATA_SCIENCE','TAX_ACCOUNTING','TECHNO_MANAGEMENT','FINE_ARTS','KOREAN_PAINTING','WESTERN_PAINTING','DESIGN','PERFORMING_ART','SPORTS_SCIENCE','HEALTH_EXERCISE','KOREAN_EDUCATION','ENGLISH_EDUCATION','JAPANESE_EDUCATION','MATH_EDUCATION','PHYSICAL_EDUCATION','EARLY_CHILDHOOD_EDUCATION','HISTORY_EDUCATION','ETHICS_EDUCATION','URBAN_ADMINISTRATION','CIVIL_ENVIRONMENT_ENGINEERING','ENVIRONMENT_ENGINEERING','URBAN_ENGINEERING','URBAN_ARCHITECTURE','URBAN_ARCHITECTURE_ENGINEERING','URBAN_ARCHITECTURE_ARCHITECTURE','LIFE_SCIENCE','LIFE_SCIENCE_MOLECULAR','BIOENGINEERING','BIOENGINEERING_NANO','LIBERAL_ARTS','INTERNATIONAL_LIBERAL_ARTS','CONVERGENCE','NORTHEAST_ASIAN_TRADE','SMART_LOGISTICS_ENGINEERING','IBE','LAW','GENERAL','GENERAL_ELECTIVE','TEACHING','MILITARY_SCIENCE','HUSS_OTHER_UNIVERSITY','HUSS_INCLUSIVE_SOCIAL_INITIATIVE','OPTICAL_ELECTRONICS_LINKED','LOGISTICS_LINKED','FUTURE_EDUCATION_DESIGN_LINKED','FUTURE_CAR_LINKED','SEMICONDUCTOR_CONVERGENCE','SOCIAL_DATA_SCIENCE_LINKED','HUMANITIES_CULTURE_ART_PLANNING_LINKED','INTELLIGENT_ROBOT_SYSTEM_LINKED','CREATIVE_DESIGN_LINKED','INTERNATIONAL_DEVELOPMENT_COOPERATION_LINKED','ECONOMICS_EVENING','TRADE_EVENING','ELECTRONICS_ENGINEERING_DEPARTMENT','ELECTRONICS_ENGINEERING_MAJOR','URBAN_ENVIRONMENT_DIVISION','LIFE_SCIENCE_DIVISION','BIOENGINEERING_DIVISION','UNKNOWN')
    COLLATE utf8mb4_general_ci NULL;

ALTER TABLE keyword MODIFY COLUMN department
    ENUM('KOREAN','ENGLISH','GERMAN','FRENCH','JAPANESE','CHINESE','MATHEMATICS','PHYSICS','CHEMISTRY','FASHION','MARINE','SOCIAL_WELFARE','MEDIA_COMMUNICATION','LIBRARY_INFO','CREATIVE_HRD','PUBLIC_ADMINISTRATION','POLITICS_DIPLOMACY','ECONOMICS','TRADE','CONSUMER_SCIENCE','ENERGY_CHEMICAL','ELECTRICAL_ENGINEERING','ELECTRONICS_ENGINEERING','INDUSTRIAL_MANAGEMENT','MATERIAL_SCIENCE','MECHANICAL_ENGINEERING','BIO_ROBOTICS_ENGINEERING','SAFETY_ENGINEERING','COMPUTER_ENGINEERING','INFORMATION_COMMUNICATION_ENGINEERING','EMBEDDED_SYSTEM','BUSINESS_ADMINISTRATION','DATA_SCIENCE','TAX_ACCOUNTING','TECHNO_MANAGEMENT','FINE_ARTS','KOREAN_PAINTING','WESTERN_PAINTING','DESIGN','PERFORMING_ART','SPORTS_SCIENCE','HEALTH_EXERCISE','KOREAN_EDUCATION','ENGLISH_EDUCATION','JAPANESE_EDUCATION','MATH_EDUCATION','PHYSICAL_EDUCATION','EARLY_CHILDHOOD_EDUCATION','HISTORY_EDUCATION','ETHICS_EDUCATION','URBAN_ADMINISTRATION','CIVIL_ENVIRONMENT_ENGINEERING','ENVIRONMENT_ENGINEERING','URBAN_ENGINEERING','URBAN_ARCHITECTURE','URBAN_ARCHITECTURE_ENGINEERING','URBAN_ARCHITECTURE_ARCHITECTURE','LIFE_SCIENCE','LIFE_SCIENCE_MOLECULAR','BIOENGINEERING','BIOENGINEERING_NANO','LIBERAL_ARTS','INTERNATIONAL_LIBERAL_ARTS','CONVERGENCE','NORTHEAST_ASIAN_TRADE','SMART_LOGISTICS_ENGINEERING','IBE','LAW','GENERAL','GENERAL_ELECTIVE','TEACHING','MILITARY_SCIENCE','HUSS_OTHER_UNIVERSITY','HUSS_INCLUSIVE_SOCIAL_INITIATIVE','OPTICAL_ELECTRONICS_LINKED','LOGISTICS_LINKED','FUTURE_EDUCATION_DESIGN_LINKED','FUTURE_CAR_LINKED','SEMICONDUCTOR_CONVERGENCE','SOCIAL_DATA_SCIENCE_LINKED','HUMANITIES_CULTURE_ART_PLANNING_LINKED','INTELLIGENT_ROBOT_SYSTEM_LINKED','CREATIVE_DESIGN_LINKED','INTERNATIONAL_DEVELOPMENT_COOPERATION_LINKED','ECONOMICS_EVENING','TRADE_EVENING','ELECTRONICS_ENGINEERING_DEPARTMENT','ELECTRONICS_ENGINEERING_MAJOR','URBAN_ENVIRONMENT_DIVISION','LIFE_SCIENCE_DIVISION','BIOENGINEERING_DIVISION','UNKNOWN')
    COLLATE utf8mb4_general_ci NULL;

ALTER TABLE member MODIFY COLUMN department
    ENUM('KOREAN','ENGLISH','GERMAN','FRENCH','JAPANESE','CHINESE','MATHEMATICS','PHYSICS','CHEMISTRY','FASHION','MARINE','SOCIAL_WELFARE','MEDIA_COMMUNICATION','LIBRARY_INFO','CREATIVE_HRD','PUBLIC_ADMINISTRATION','POLITICS_DIPLOMACY','ECONOMICS','TRADE','CONSUMER_SCIENCE','ENERGY_CHEMICAL','ELECTRICAL_ENGINEERING','ELECTRONICS_ENGINEERING','INDUSTRIAL_MANAGEMENT','MATERIAL_SCIENCE','MECHANICAL_ENGINEERING','BIO_ROBOTICS_ENGINEERING','SAFETY_ENGINEERING','COMPUTER_ENGINEERING','INFORMATION_COMMUNICATION_ENGINEERING','EMBEDDED_SYSTEM','BUSINESS_ADMINISTRATION','DATA_SCIENCE','TAX_ACCOUNTING','TECHNO_MANAGEMENT','FINE_ARTS','KOREAN_PAINTING','WESTERN_PAINTING','DESIGN','PERFORMING_ART','SPORTS_SCIENCE','HEALTH_EXERCISE','KOREAN_EDUCATION','ENGLISH_EDUCATION','JAPANESE_EDUCATION','MATH_EDUCATION','PHYSICAL_EDUCATION','EARLY_CHILDHOOD_EDUCATION','HISTORY_EDUCATION','ETHICS_EDUCATION','URBAN_ADMINISTRATION','CIVIL_ENVIRONMENT_ENGINEERING','ENVIRONMENT_ENGINEERING','URBAN_ENGINEERING','URBAN_ARCHITECTURE','URBAN_ARCHITECTURE_ENGINEERING','URBAN_ARCHITECTURE_ARCHITECTURE','LIFE_SCIENCE','LIFE_SCIENCE_MOLECULAR','BIOENGINEERING','BIOENGINEERING_NANO','LIBERAL_ARTS','INTERNATIONAL_LIBERAL_ARTS','CONVERGENCE','NORTHEAST_ASIAN_TRADE','SMART_LOGISTICS_ENGINEERING','IBE','LAW','GENERAL','GENERAL_ELECTIVE','TEACHING','MILITARY_SCIENCE','HUSS_OTHER_UNIVERSITY','HUSS_INCLUSIVE_SOCIAL_INITIATIVE','OPTICAL_ELECTRONICS_LINKED','LOGISTICS_LINKED','FUTURE_EDUCATION_DESIGN_LINKED','FUTURE_CAR_LINKED','SEMICONDUCTOR_CONVERGENCE','SOCIAL_DATA_SCIENCE_LINKED','HUMANITIES_CULTURE_ART_PLANNING_LINKED','INTELLIGENT_ROBOT_SYSTEM_LINKED','CREATIVE_DESIGN_LINKED','INTERNATIONAL_DEVELOPMENT_COOPERATION_LINKED','ECONOMICS_EVENING','TRADE_EVENING','ELECTRONICS_ENGINEERING_DEPARTMENT','ELECTRONICS_ENGINEERING_MAJOR','URBAN_ENVIRONMENT_DIVISION','LIFE_SCIENCE_DIVISION','BIOENGINEERING_DIVISION','UNKNOWN')
    COLLATE utf8mb4_general_ci NULL;

ALTER TABLE schedule MODIFY COLUMN department
    ENUM('KOREAN','ENGLISH','GERMAN','FRENCH','JAPANESE','CHINESE','MATHEMATICS','PHYSICS','CHEMISTRY','FASHION','MARINE','SOCIAL_WELFARE','MEDIA_COMMUNICATION','LIBRARY_INFO','CREATIVE_HRD','PUBLIC_ADMINISTRATION','POLITICS_DIPLOMACY','ECONOMICS','TRADE','CONSUMER_SCIENCE','ENERGY_CHEMICAL','ELECTRICAL_ENGINEERING','ELECTRONICS_ENGINEERING','INDUSTRIAL_MANAGEMENT','MATERIAL_SCIENCE','MECHANICAL_ENGINEERING','BIO_ROBOTICS_ENGINEERING','SAFETY_ENGINEERING','COMPUTER_ENGINEERING','INFORMATION_COMMUNICATION_ENGINEERING','EMBEDDED_SYSTEM','BUSINESS_ADMINISTRATION','DATA_SCIENCE','TAX_ACCOUNTING','TECHNO_MANAGEMENT','FINE_ARTS','KOREAN_PAINTING','WESTERN_PAINTING','DESIGN','PERFORMING_ART','SPORTS_SCIENCE','HEALTH_EXERCISE','KOREAN_EDUCATION','ENGLISH_EDUCATION','JAPANESE_EDUCATION','MATH_EDUCATION','PHYSICAL_EDUCATION','EARLY_CHILDHOOD_EDUCATION','HISTORY_EDUCATION','ETHICS_EDUCATION','URBAN_ADMINISTRATION','CIVIL_ENVIRONMENT_ENGINEERING','ENVIRONMENT_ENGINEERING','URBAN_ENGINEERING','URBAN_ARCHITECTURE','URBAN_ARCHITECTURE_ENGINEERING','URBAN_ARCHITECTURE_ARCHITECTURE','LIFE_SCIENCE','LIFE_SCIENCE_MOLECULAR','BIOENGINEERING','BIOENGINEERING_NANO','LIBERAL_ARTS','INTERNATIONAL_LIBERAL_ARTS','CONVERGENCE','NORTHEAST_ASIAN_TRADE','SMART_LOGISTICS_ENGINEERING','IBE','LAW','GENERAL','GENERAL_ELECTIVE','TEACHING','MILITARY_SCIENCE','HUSS_OTHER_UNIVERSITY','HUSS_INCLUSIVE_SOCIAL_INITIATIVE','OPTICAL_ELECTRONICS_LINKED','LOGISTICS_LINKED','FUTURE_EDUCATION_DESIGN_LINKED','FUTURE_CAR_LINKED','SEMICONDUCTOR_CONVERGENCE','SOCIAL_DATA_SCIENCE_LINKED','HUMANITIES_CULTURE_ART_PLANNING_LINKED','INTELLIGENT_ROBOT_SYSTEM_LINKED','CREATIVE_DESIGN_LINKED','INTERNATIONAL_DEVELOPMENT_COOPERATION_LINKED','ECONOMICS_EVENING','TRADE_EVENING','ELECTRONICS_ENGINEERING_DEPARTMENT','ELECTRONICS_ENGINEERING_MAJOR','URBAN_ENVIRONMENT_DIVISION','LIFE_SCIENCE_DIVISION','BIOENGINEERING_DIVISION','UNKNOWN')
    COLLATE utf8mb4_general_ci NULL;

ALTER TABLE school_department MODIFY COLUMN notice_department
    ENUM('KOREAN','ENGLISH','GERMAN','FRENCH','JAPANESE','CHINESE','MATHEMATICS','PHYSICS','CHEMISTRY','FASHION','MARINE','SOCIAL_WELFARE','MEDIA_COMMUNICATION','LIBRARY_INFO','CREATIVE_HRD','PUBLIC_ADMINISTRATION','POLITICS_DIPLOMACY','ECONOMICS','TRADE','CONSUMER_SCIENCE','ENERGY_CHEMICAL','ELECTRICAL_ENGINEERING','ELECTRONICS_ENGINEERING','INDUSTRIAL_MANAGEMENT','MATERIAL_SCIENCE','MECHANICAL_ENGINEERING','BIO_ROBOTICS_ENGINEERING','SAFETY_ENGINEERING','COMPUTER_ENGINEERING','INFORMATION_COMMUNICATION_ENGINEERING','EMBEDDED_SYSTEM','BUSINESS_ADMINISTRATION','DATA_SCIENCE','TAX_ACCOUNTING','TECHNO_MANAGEMENT','FINE_ARTS','KOREAN_PAINTING','WESTERN_PAINTING','DESIGN','PERFORMING_ART','SPORTS_SCIENCE','HEALTH_EXERCISE','KOREAN_EDUCATION','ENGLISH_EDUCATION','JAPANESE_EDUCATION','MATH_EDUCATION','PHYSICAL_EDUCATION','EARLY_CHILDHOOD_EDUCATION','HISTORY_EDUCATION','ETHICS_EDUCATION','URBAN_ADMINISTRATION','CIVIL_ENVIRONMENT_ENGINEERING','ENVIRONMENT_ENGINEERING','URBAN_ENGINEERING','URBAN_ARCHITECTURE','URBAN_ARCHITECTURE_ENGINEERING','URBAN_ARCHITECTURE_ARCHITECTURE','LIFE_SCIENCE','LIFE_SCIENCE_MOLECULAR','BIOENGINEERING','BIOENGINEERING_NANO','LIBERAL_ARTS','INTERNATIONAL_LIBERAL_ARTS','CONVERGENCE','NORTHEAST_ASIAN_TRADE','SMART_LOGISTICS_ENGINEERING','IBE','LAW','GENERAL','GENERAL_ELECTIVE','TEACHING','MILITARY_SCIENCE','HUSS_OTHER_UNIVERSITY','HUSS_INCLUSIVE_SOCIAL_INITIATIVE','OPTICAL_ELECTRONICS_LINKED','LOGISTICS_LINKED','FUTURE_EDUCATION_DESIGN_LINKED','FUTURE_CAR_LINKED','SEMICONDUCTOR_CONVERGENCE','SOCIAL_DATA_SCIENCE_LINKED','HUMANITIES_CULTURE_ART_PLANNING_LINKED','INTELLIGENT_ROBOT_SYSTEM_LINKED','CREATIVE_DESIGN_LINKED','INTERNATIONAL_DEVELOPMENT_COOPERATION_LINKED','ECONOMICS_EVENING','TRADE_EVENING','ELECTRONICS_ENGINEERING_DEPARTMENT','ELECTRONICS_ENGINEERING_MAJOR','URBAN_ENVIRONMENT_DIVISION','LIFE_SCIENCE_DIVISION','BIOENGINEERING_DIVISION','UNKNOWN')
    COLLATE utf8mb4_general_ci NULL;

-- 1-3  College ENUM (course.college)  HUSS 제거, UNKNOWN 등 추가
ALTER TABLE course MODIFY COLUMN college
    ENUM('COLLEGE_OF_HUMANITIES','COLLEGE_OF_NATURAL_SCIENCES','COLLEGE_OF_SOCIAL_SCIENCES','COLLEGE_OF_GLOBAL_ECONOMICS_AND_TRADE','COLLEGE_OF_ENGINEERING','COLLEGE_OF_INFORMATION_TECHNOLOGY','COLLEGE_OF_BUSINESS_ADMINISTRATION','COLLEGE_OF_ARTS_AND_PHYSICAL_EDUCATION','COLLEGE_OF_EDUCATION','COLLEGE_OF_URBAN_SCIENCE','COLLEGE_OF_LIFE_SCIENCES_AND_BIOTECHNOLOGY','COLLEGE_OF_INTERDISCIPLINARY_STUDIES','COLLEGE_OF_NULL','GENERAL','GENERAL_ELECTIVE','TEACHING','MILITARY_SCIENCE','ETC','NO_COLLEGE','LAW_NO_COLLEGE','UNKNOWN')
    COLLATE utf8mb4_general_ci NOT NULL;

-- 1-4  course_offering enum 컬럼 8개 DROP
ALTER TABLE course_offering
    DROP COLUMN dept_name,
    DROP COLUMN college_name,
    DROP COLUMN hy_name,
    DROP COLUMN isu_name,
    DROP COLUMN isu_fld_name,
    DROP COLUMN ssup_type_name,
    DROP COLUMN cnctr_isu_name,
    DROP COLUMN english_name;

-- 1-5  [prod 만] course_offering 인덱스 3개 (dev 는 이미 존재 → dev 에서는 실행하지 말 것)
CREATE INDEX idx_course_offering_open_sort  ON course_offering (semester_id, hy_code, isu_code, subject_number);
CREATE INDEX idx_course_offering_department ON course_offering (semester_id, dept_code);
CREATE INDEX idx_course_offering_completion ON course_offering (semester_id, isu_code, isu_fld_code);


-- ============== 여기서 새 코드 배포 / 기동 ==============


-- ===================== PHASE 2 : *_code 백필 =====================

-- 2-1
UPDATE course_offering
SET college_code = CASE college_name_raw
    WHEN '인문대학'              THEN 'A000'
    WHEN '자연과학대학'          THEN 'B000'
    WHEN '사회과학대학'          THEN 'C000'
    WHEN '공과대학'              THEN 'E000'
    WHEN '정보기술대학'          THEN 'I000'
    WHEN '경영대학'              THEN 'J000'
    WHEN '교양'                  THEN 'X000'
    WHEN '일선'                  THEN 'W000'
    WHEN '교직'                  THEN 'Y000'
    WHEN '군사학'                THEN 'Z000'
    WHEN '기타'                  THEN 'V000'
    WHEN '글로벌정경대학'        THEN '0000689'
    WHEN '예술체육대학'          THEN '0000190'
    WHEN '사범대학'              THEN '0000063'
    WHEN '도시과학대학'          THEN '0000033'
    WHEN '생명과학기술대학'      THEN '0000182'
    WHEN '융합자유전공대학'      THEN '0000837'
    WHEN '단과대구분없음'        THEN '0000465'
    WHEN '단과대구분없음(법학)'  THEN '0000706'
END
WHERE college_code IS NULL AND college_name_raw IS NOT NULL;

-- 2-2
UPDATE course_offering
SET hy_code = CASE hy_name_raw
    WHEN '전학년' THEN '0'
    WHEN '1'      THEN '1'
    WHEN '2'      THEN '2'
    WHEN '3'      THEN '3'
    WHEN '4'      THEN '4'
END
WHERE hy_code IS NULL AND hy_name_raw IS NOT NULL;

-- 2-3
UPDATE course_offering
SET isu_code = CASE isu_name_raw
    WHEN '기초교양'  THEN '11'
    WHEN '핵심교양'  THEN '21'
    WHEN '심화교양'  THEN '23'
    WHEN '전공기초'  THEN '25'
    WHEN '전공핵심'  THEN '31'
    WHEN '전공심화'  THEN '41'
    WHEN '교직'      THEN '50'
    WHEN '군사학'    THEN '70'
    WHEN '일반선택'  THEN '80'
END
WHERE isu_code IS NULL AND isu_name_raw IS NOT NULL;

-- 2-4
UPDATE course_offering
SET english_code = CASE english_name_raw
    WHEN '비대상'         THEN '0'
    WHEN '원어강의(EN)'   THEN '1'
    WHEN '글로벌강의(ES)' THEN '2'
END
WHERE english_code IS NULL AND english_name_raw IS NOT NULL;

-- 2-5
UPDATE course_offering
SET cnctr_isu_code = CASE cnctr_isu_name_raw
    WHEN '일반(1~15주)'  THEN '0'
    WHEN '집중A(1~8주)'  THEN '1'
    WHEN '집중C(1~12주)' THEN '3'
END
WHERE cnctr_isu_code IS NULL AND cnctr_isu_name_raw IS NOT NULL;

-- 2-6
UPDATE course_offering
SET isu_fld_code = CASE isu_fld_name_raw
    WHEN '학문의기초'      THEN '161'
    WHEN '기초과학ㆍ공학'  THEN '162'
    WHEN '기초과학·공학'   THEN '162'
    WHEN '(핵심)INU세미나' THEN '171'
    WHEN '(핵심)인문'      THEN '172'
    WHEN '(핵심)사회'      THEN '173'
    WHEN '(핵심)과학기술'  THEN '174'
    WHEN '(핵심)예술체육'  THEN '175'
    WHEN '(핵심)외국어'    THEN '176'
    WHEN '인문'            THEN '182'
    WHEN '사회'            THEN '183'
    WHEN '과학기술'        THEN '184'
    WHEN '예술체육'        THEN '185'
    WHEN '외국어'          THEN '186'
    WHEN '전공기초'        THEN '31'
    WHEN '전공핵심'        THEN '34'
    WHEN '전공심화'        THEN '35'
    WHEN '교직'            THEN '51'
    WHEN '군사학'          THEN '71'
    WHEN '일반선택'        THEN '81'
END
WHERE isu_fld_code IS NULL AND isu_fld_name_raw IS NOT NULL;

-- 2-7
UPDATE course_offering
SET ssup_type_code = CASE ssup_type_name_raw
    WHEN '강의(이론)'             THEN '1'
    WHEN '실험실습'               THEN '2'
    WHEN '체육실기'               THEN '3'
    WHEN '미술실기'               THEN '4'
    WHEN '이론실험실습'           THEN '5'
    WHEN '열린사이버대학(OCU)'    THEN '7'
    WHEN 'e-Learning'             THEN '8'
    WHEN '담장너머~,사회봉사(1)'  THEN '11'
    WHEN '사회봉사(2)'            THEN '12'
    WHEN '사회봉사(3)'            THEN '13'
    WHEN '자기설계세미나'         THEN '17'
    WHEN '이론(어학)'             THEN '20'
    WHEN 'RISE(시간표 있음)'      THEN '21'
    WHEN 'RISE(시간표 없음)'      THEN '22'
    WHEN '예술체육실기'           THEN '23'
    WHEN '온라인혼합형강좌'       THEN '24'
    WHEN 'K-MOOC'                 THEN '25'
    WHEN 'e-Learning(HUSS)'       THEN '26'
    WHEN '온라인혼합형강좌(HUSS)' THEN '27'
    WHEN '현장형(HUSS)'           THEN '28'
END
WHERE ssup_type_code IS NULL AND ssup_type_name_raw IS NOT NULL;

-- 2-8  dept_code  (실제 dept_name_raw DISTINCT 104개 전수)
UPDATE course_offering
SET dept_code = CASE dept_name_raw
    WHEN '국어국문학과'              THEN 'AIA1'
    WHEN '영어영문학과'              THEN 'AIB1'
    WHEN '중어중국학과'              THEN 'AID1'
    WHEN '독어독문학과'              THEN 'AIE1'
    WHEN '불어불문학과'              THEN 'AIF1'
    WHEN '일본지역문화학과'          THEN '0000793'
    WHEN '일어일문학과'              THEN '0000793'
    WHEN '수학과'                    THEN 'BKA1'
    WHEN '물리학과'                  THEN 'BKB1'
    WHEN '화학과'                    THEN 'BKC1'
    WHEN '패션산업학과'              THEN 'BLB1'
    WHEN '해양학과'                  THEN '0000189'
    WHEN '사회복지학과'              THEN '0000144'
    WHEN '미디어커뮤니케이션학과'    THEN '0000794'
    WHEN '신문방송학과'              THEN '0000794'
    WHEN '문헌정보학과'              THEN '0000053'
    WHEN '창의인재개발학과'          THEN '0000054'
    WHEN '행정학과'                  THEN '0000698'
    WHEN '정치외교학과'              THEN '0000699'
    WHEN '경제학과'                  THEN '0000700'
    WHEN '경제학과(야)'              THEN '0000701'
    WHEN '무역학부'                  THEN '0000913'
    WHEN '무역학부(야)'              THEN '0000703'
    WHEN '소비자학과'                THEN '0000704'
    WHEN '소비자ㆍ아동학과'          THEN '0000704'
    WHEN '에너지화학공학과'          THEN '0000055'
    WHEN '전기공학과'                THEN 'EPB1'
    WHEN '전자공학부'                THEN '0000813'
    WHEN '전자공학과'                THEN 'EPC1'
    WHEN '전자공학과(야)'            THEN 'EPC1'
    WHEN '전자공학전공'              THEN '0000828'
    WHEN '산업경영공학과'            THEN 'EPG1'
    WHEN '산업경영공학과(야)'        THEN 'EPG1'
    WHEN '신소재공학과'              THEN '0000076'
    WHEN '기계공학과'                THEN '0000459'
    WHEN '기계공학과(야)'            THEN '0000459'
    WHEN '메카트로닉스공학과'        THEN '0000814'
    WHEN '바이오-로봇시스템공학과'   THEN '0000814'
    WHEN '안전공학과'                THEN '0000075'
    WHEN '컴퓨터공학부'              THEN '0000077'
    WHEN '컴퓨터공학부(야)'          THEN '0000077'
    WHEN '정보통신공학과'            THEN 'IAB1'
    WHEN '임베디드시스템공학과'      THEN '0000042'
    WHEN '경영학부'                  THEN 'JA01'
    WHEN '데이터과학과'              THEN '0000812'
    WHEN '세무회계학과'              THEN '0000057'
    WHEN '조형예술학부'              THEN '0000192'
    WHEN '한국화전공'                THEN '0000193'
    WHEN '서양화전공'                THEN '0000194'
    WHEN '디자인학부'                THEN '0000195'
    WHEN '공연예술학과'              THEN '0000196'
    WHEN '스포츠과학부'              THEN '0000815'
    WHEN '체육학부'                  THEN '0000815'
    WHEN '운동건강학부'              THEN '0000191'
    WHEN '국어교육과'                THEN '0000064'
    WHEN '영어교육과'                THEN '0000065'
    WHEN '일어교육과'                THEN '0000066'
    WHEN '수학교육과'                THEN '0000067'
    WHEN '체육교육과'                THEN '0000068'
    WHEN '유아교육과'                THEN '0000069'
    WHEN '역사교육과'                THEN '0000070'
    WHEN '윤리교육과'                THEN '0000071'
    WHEN '도시행정학과'              THEN '0000073'
    WHEN '건설환경공학전공'          THEN '0000156'
    WHEN '건설환경공학부'            THEN '0000156'
    WHEN '환경공학전공'              THEN '0000157'
    WHEN '도시환경공학부'            THEN '0000034'
    WHEN '도시공학과'                THEN '0000463'
    WHEN '도시건축학부'              THEN '0000038'
    WHEN '건축공학전공'              THEN '0000160'
    WHEN '도시건축학전공'            THEN '0000464'
    WHEN '생명과학부'                THEN '0000183'
    WHEN '생명과학전공'              THEN '0000184'
    WHEN '분자의생명전공'            THEN '0000185'
    WHEN '생명공학부'                THEN '0000186'
    WHEN '생명공학전공'              THEN '0000187'
    WHEN '나노바이오공학전공'        THEN '0000833'
    WHEN '나노바이오전공'            THEN '0000833'
    WHEN '자유전공학부'              THEN '0000838'
    WHEN '법학부'                    THEN '0000707'
    WHEN 'IBE전공'                   THEN '0000832'
    WHEN '한국통상전공'              THEN '0000832'
    WHEN '스마트물류공학전공'        THEN '0000818'
    WHEN '동북아국제통상전공'        THEN '0000817'
    WHEN '동북아통상전공'            THEN '0000817'
    WHEN '동북아국제통상학부'        THEN '0000817'
    WHEN '반도체융합전공'            THEN '0000829'
    WHEN '광전자공학전공(연계)'      THEN 'VAB1'
    WHEN '물류학전공(연계)'          THEN 'VAC1'
    WHEN '미래교육디자인연계전공'    THEN '0000849'
    WHEN '미래자동차연계전공'        THEN '0000789'
    WHEN '소셜데이터사이언스연계전공' THEN '0000678'
    WHEN '인문문화예술기획연계전공'   THEN '0000677'
    WHEN '지능형로봇시스템연계전공'   THEN '0000912'
    WHEN '지능로봇연계전공'          THEN '0000912'
    WHEN '창의적디자인연계전공'      THEN '0000616'
    WHEN '교양'                      THEN 'XAA0'
    WHEN '일선'                      THEN 'WAA0'
    WHEN '교직'                      THEN 'YAA0'
    WHEN '군사학'                    THEN 'ZAA0'
END
WHERE dept_code IS NULL AND dept_name_raw IS NOT NULL;


-- ===================== PHASE 3 : 검증 =====================

SELECT
    SUM(dept_code       IS NULL) AS dept_null,
    SUM(college_code    IS NULL) AS college_null,
    SUM(hy_code         IS NULL) AS hy_null,
    SUM(isu_code        IS NULL) AS isu_null,
    SUM(isu_fld_code    IS NULL) AS isu_fld_null,
    SUM(ssup_type_code  IS NULL) AS ssup_null,
    SUM(cnctr_isu_code  IS NULL) AS cnctr_null,
    SUM(english_code    IS NULL) AS english_null,
    COUNT(*)                     AS total
FROM course_offering;

SELECT dept_name_raw, COUNT(*) AS cnt
FROM course_offering
WHERE dept_code IS NULL
GROUP BY dept_name_raw
ORDER BY cnt DESC;

SELECT TABLE_NAME, COLUMN_NAME,
       CHAR_LENGTH(COLUMN_TYPE) - CHAR_LENGTH(REPLACE(COLUMN_TYPE, ',', '')) + 1 AS enum_value_count
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND DATA_TYPE = 'enum'
  AND (COLUMN_TYPE LIKE '%KOREAN%' OR COLUMN_TYPE LIKE '%COLLEGE_OF_HUMANITIES%')
ORDER BY TABLE_NAME, COLUMN_NAME;
