{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jodd",
    "module": "jodd-util",
    "version": "6.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "zjbjdg3murf33oceplhmaypu44"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jodd-util-6.3.0.jar",
          "url": "jodd-util-6.3.0.jar",
          "size": 337658,
          "sha512": "55a06ba2f46c910897ac06fb380fc860d7b290069f93f1e83b085b53d93977cca43d1cbc9a75338eb2174a231f863d531a72744fc662bf8b8357686746f391f2",
          "sha256": "e5c676715897124101f74900dd1f98ebbcad9da3ab2dffbac6e7712612094427",
          "sha1": "1568f4d0f60dee75c8881fb0ebe44f0ab9fa3b38",
          "md5": "fba2683e40999886094742646d695521"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jodd-util-6.3.0.jar",
          "url": "jodd-util-6.3.0.jar",
          "size": 337658,
          "sha512": "55a06ba2f46c910897ac06fb380fc860d7b290069f93f1e83b085b53d93977cca43d1cbc9a75338eb2174a231f863d531a72744fc662bf8b8357686746f391f2",
          "sha256": "e5c676715897124101f74900dd1f98ebbcad9da3ab2dffbac6e7712612094427",
          "sha1": "1568f4d0f60dee75c8881fb0ebe44f0ab9fa3b38",
          "md5": "fba2683e40999886094742646d695521"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jodd-util-6.3.0-sources.jar",
          "url": "jodd-util-6.3.0-sources.jar",
          "size": 302050,
          "sha512": "b5b4908bddb8a36ed6e19d7860a09ff393e4c2401f394bae1cc4d3e6fce931bfb34d8688d0f7c4b73dc3182e63756dcf4b3a80d0380f764731231882b62be726",
          "sha256": "15b9eb016cc8fe52de6332cd9fb23eadba29393b0087635294aa2e23586b809f",
          "sha1": "629fc0a7c86888e9b78a2fd146b495f767f8113b",
          "md5": "5533f508410081d4bd1eee03015c08af"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jodd-util-6.3.0-javadoc.jar",
          "url": "jodd-util-6.3.0-javadoc.jar",
          "size": 584271,
          "sha512": "3a03a740bd67c0cc49f6bf96efc6cf2cef58c9095711915daee43bd76f4a8361814714ecf19b95f9b93b0764e40a1ccc9bdcb1ce32445bb139ae7f02a3184406",
          "sha256": "41f0e74191a87e7ebbfc91a3444a99fe31c0db89a746851e9222ef64f7b05c5a",
          "sha1": "bfa822f7d8a14374f0ba59f6b16ce26ef8fcf11b",
          "md5": "c56078b5447c61062697f9c3ed472d23"
        }
      ]
    }
  ]
}
