app.local-auth.enabled=true
app.local-auth.seed-users[0].student-id=local-user
app.local-auth.seed-users[0].password=local-user
app.local-auth.seed-users[0].roles[0]=ROLE_USER

app.local-auth.seed-users[1].student-id=local-admin
app.local-auth.seed-users[1].password=local-admin
app.local-auth.seed-users[1].roles[0]=ROLE_ADMIN
