{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sentry",
    "module": "sentry-android-gradle-plugin",
    "version": "5.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "sentry-android-gradle-plugin-5.1.0.jar",
          "url": "sentry-android-gradle-plugin-5.1.0.jar",
          "size": 39063189,
          "sha512": "4ea6d8e604832bb423c45559805d26c8ee6b2b284f87ae16053411d954e9c3368ac0195b85423122ae565c60c2e2f4c8807ebba1efb699e8fdbddfdf2facc9d0",
          "sha256": "51f46815264203e1f5ca530d56b971c1613ee9d75595d900c20fc55e1e297e6d",
          "sha1": "0dc4e3c915be280b926d6083c4080eccaaa5553e",
          "md5": "5c1df7e8f575f669c3ccb5c77a8b7718"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "sentry-android-gradle-plugin-5.1.0.jar",
          "url": "sentry-android-gradle-plugin-5.1.0.jar",
          "size": 39063189,
          "sha512": "4ea6d8e604832bb423c45559805d26c8ee6b2b284f87ae16053411d954e9c3368ac0195b85423122ae565c60c2e2f4c8807ebba1efb699e8fdbddfdf2facc9d0",
          "sha256": "51f46815264203e1f5ca530d56b971c1613ee9d75595d900c20fc55e1e297e6d",
          "sha1": "0dc4e3c915be280b926d6083c4080eccaaa5553e",
          "md5": "5c1df7e8f575f669c3ccb5c77a8b7718"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sentry-android-gradle-plugin-5.1.0.jar",
          "url": "sentry-android-gradle-plugin-5.1.0.jar",
          "size": 39063189,
          "sha512": "4ea6d8e604832bb423c45559805d26c8ee6b2b284f87ae16053411d954e9c3368ac0195b85423122ae565c60c2e2f4c8807ebba1efb699e8fdbddfdf2facc9d0",
          "sha256": "51f46815264203e1f5ca530d56b971c1613ee9d75595d900c20fc55e1e297e6d",
          "sha1": "0dc4e3c915be280b926d6083c4080eccaaa5553e",
          "md5": "5c1df7e8f575f669c3ccb5c77a8b7718"
        }
      ]
    }
  ]
}
