{
  "formatVersion": "1.1",
  "component": {
    "group": "io.projectreactor",
    "module": "reactor-core",
    "version": "3.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "reactor-core-3.6.1.jar",
          "url": "reactor-core-3.6.1.jar",
          "size": 1867913,
          "sha512": "85f4f1480fbd6e9fbbabb6a0554ffb639e1051fd7fda300413bc0cfc48e0ea31c3f32dfc39333e45b54dc8bfcfd3004dc6badb2b4ab1c47a081a81dc46b7315d",
          "sha256": "74dbf3fe0eb94e326e7c98ce14e9b4996c1d50d0e661fc05387f34f4babaeb11",
          "sha1": "a3be3c85954485cbb3751205fe56fa42ee9efa4c",
          "md5": "fcda68eed184cc50676bcd9450f5dccc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "reactor-core-3.6.1.jar",
          "url": "reactor-core-3.6.1.jar",
          "size": 1867913,
          "sha512": "85f4f1480fbd6e9fbbabb6a0554ffb639e1051fd7fda300413bc0cfc48e0ea31c3f32dfc39333e45b54dc8bfcfd3004dc6badb2b4ab1c47a081a81dc46b7315d",
          "sha256": "74dbf3fe0eb94e326e7c98ce14e9b4996c1d50d0e661fc05387f34f4babaeb11",
          "sha1": "a3be3c85954485cbb3751205fe56fa42ee9efa4c",
          "md5": "fcda68eed184cc50676bcd9450f5dccc"
        }
      ]
    }
  ]
}
