{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sentry",
    "module": "sentry-jdbc",
    "version": "8.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.sentry",
          "module": "sentry",
          "version": {
            "requires": "8.1.0"
          }
        },
        {
          "group": "p6spy",
          "module": "p6spy",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "sentry-jdbc-8.1.0.jar",
          "url": "sentry-jdbc-8.1.0.jar",
          "size": 7294,
          "sha512": "678ffd58345f813c71d9d77e44b95172907880f9f5c91fa209dc051fe9e58e5d32b0ba7eb8a9338fc3ba33b89ae17068f3615286908ca586c986d9dd5376c661",
          "sha256": "e658c2e67c97d82529c3b5aee5af12a73ef50c3723f601904afe2a71e73be08e",
          "sha1": "9609abd4b3c436e1649bd4256e1818369ce01471",
          "md5": "d392183a7ea11f220e6876b519dccca6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.sentry",
          "module": "sentry",
          "version": {
            "requires": "8.1.0"
          }
        },
        {
          "group": "p6spy",
          "module": "p6spy",
          "version": {
            "requires": "3.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "sentry-jdbc-8.1.0.jar",
          "url": "sentry-jdbc-8.1.0.jar",
          "size": 7294,
          "sha512": "678ffd58345f813c71d9d77e44b95172907880f9f5c91fa209dc051fe9e58e5d32b0ba7eb8a9338fc3ba33b89ae17068f3615286908ca586c986d9dd5376c661",
          "sha256": "e658c2e67c97d82529c3b5aee5af12a73ef50c3723f601904afe2a71e73be08e",
          "sha1": "9609abd4b3c436e1649bd4256e1818369ce01471",
          "md5": "d392183a7ea11f220e6876b519dccca6"
        }
      ]
    }
  ]
}
