package kr.inuappcenterportal.inuportal.global.exception.ex;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;

@Getter
@RequiredArgsConstructor
public enum MyErrorCode {

    USER_NOT_FOUND(HttpStatus.NOT_FOUND, "존재하지 않는 유저입니다."),
    IMAGE_NOT_FOUND(HttpStatus.NOT_FOUND, "존재하지 않는 이미지 번호입니다."),
    POST_SCRAP_LIST_NOT_FOUND(HttpStatus.NOT_FOUND, "게시글 리스트가 비어있습니다."),
    SCRAP_NOT_FOUND(HttpStatus.NOT_FOUND, "스크랩하지 않은 게시물입니다."),
    FOLDER_NOT_FOUND(HttpStatus.NOT_FOUND, "존재하지 않는 스크랩폴더입니다."),
    FOLDER_OR_POST_NOT_FOUND(HttpStatus.NOT_FOUND, "스크랩폴더나 게시글이 존재하지 않습니다."),
    USER_OR_POST_NOT_FOUND(HttpStatus.NOT_FOUND, "유저나 게시글이 존재하지 않습니다."),
    USER_OR_REPLY_NOT_FOUND(HttpStatus.NOT_FOUND, "유저나 댓글이 존재하지 않습니다."),
    NOT_REPLY_ON_REREPLY(HttpStatus.BAD_REQUEST, "대댓글에 댓글을 작성할 수 없습니다."),
    REPLY_NOT_FOUND(HttpStatus.NOT_FOUND, "존재하지 않는 댓글입니다."),
    CATEGORY_NOT_FOUND(HttpStatus.NOT_FOUND, "존재하지 않는 카테고리입니다."),
    USER_DUPLICATE_EMAIL(HttpStatus.BAD_REQUEST, "동일한 이메일이 존재합니다."),
    ONLY_SCHOOL_EMAIL(HttpStatus.BAD_REQUEST, "학교 이메일만 가입 가능합니다."),
    POST_DUPLICATE_FOLDER(HttpStatus.BAD_REQUEST, "스크랩폴더에 존재하는 게시글입니다."),
    USER_DUPLICATE_NICKNAME(HttpStatus.BAD_REQUEST, "동일한 닉네임이 존재합니다."),
    SAME_NICKNAME_UPDATE(HttpStatus.BAD_REQUEST, "입력한 닉네임과 현재 닉네임이 동일합니다."),
    USER_DUPLICATE_CATEGORY(HttpStatus.BAD_REQUEST, "동일한 카테고리가 존재합니다."),
    POST_NOT_FOUND(HttpStatus.NOT_FOUND, "존재하지 않는 게시글입니다."),
    ID_NOT_FOUND(HttpStatus.UNAUTHORIZED, "아이디가 존재하지 않습니다."),
    PASSWORD_NOT_MATCHED(HttpStatus.UNAUTHORIZED, "비밀번호가 틀립니다."),
    HAS_NOT_POST_AUTHORIZATION(HttpStatus.FORBIDDEN, "이 게시글의 수정/삭제에 대한 권한이 없습니다."),
    HAS_NOT_REPLY_AUTHORIZATION(HttpStatus.FORBIDDEN, "이 댓글의 수정/삭제에 대한 권한이 없습니다."),
    NOT_MULTIPLE_LIKE(HttpStatus.CONFLICT, "이미 좋아요를 눌렀습니다."),
    NOT_MULTIPLE_DISLIKE(HttpStatus.CONFLICT, "이미 싫어요를 눌렀습니다."),
    WRONG_TYPE_TOKEN(HttpStatus.UNAUTHORIZED, "토큰의 서명이 유효하지 않습니다."),
    UNSUPPORTED_TOKEN(HttpStatus.UNAUTHORIZED, "잘못된 형식의 토큰입니다."),
    EXPIRED_TOKEN(HttpStatus.UNAUTHORIZED, "만료된 토큰입니다."),
    UNKNOWN_TOKEN_ERROR(HttpStatus.BAD_REQUEST, "토큰의 값이 존재하지 않습니다."),
    WRONG_SORT_TYPE(HttpStatus.BAD_REQUEST, "정렬의 기준값이 올바르지 않습니다."),
    WRONG_SEARCH_TYPE(HttpStatus.BAD_REQUEST, "검색옵션이 올바르지 않습니다."),
    EMPTY_REQUEST(HttpStatus.BAD_REQUEST, "닉네임, 횃불이 아이디 모두 공백입니다."),
    NOT_BLANK_NICKNAME(HttpStatus.BAD_REQUEST, "닉네임이 빈칸 혹은 공백입니다."),
    EMAIL_NOT_AUTHORIZATION(HttpStatus.FORBIDDEN, "인증되지 않은 이메일입니다."),
    NOT_LIKE_MY_POST(HttpStatus.BAD_REQUEST, "자신의 게시글에는 추천을 할 수 없습니다."),
    NOT_LIKE_MY_REPLY(HttpStatus.BAD_REQUEST, "자신의 댓글에는 추천을 할 수 없습니다."),
    BAD_REQUEST_FIRE_AI(HttpStatus.BAD_REQUEST, "횃불이 이미지 관련 요청에 문제가 있습니다."),
    AI_IMAGE_GENERATING(HttpStatus.BAD_REQUEST, "횃불이 이미지가 생성 중 입니다."),
    STUDENT_LOGIN_ERROR(HttpStatus.UNAUTHORIZED, "학번 또는 비밀번호가 틀립니다."),
    RATED_IMAGE(HttpStatus.BAD_REQUEST, "이미 평가된 이미지입니다."),
    WEATHER_REQUEST_ERROR(HttpStatus.BAD_REQUEST, "날씨 요청에 문제가 있습니다."),
    BLOCK_MANY_SAME_POST_REPLY(HttpStatus.BAD_REQUEST, "일정 시간 동안 같은 게시글이나 댓글을 작성할 수 없습니다."),
    NOT_GENERATE_FIRE_AI_IMAGE(HttpStatus.BAD_REQUEST, "횃불이 이미지가 생성 중 입니다."),
    NOT_FOUND_COUNCIL_NOTICE(HttpStatus.NOT_FOUND, "존재하지 않는 총학생회 공지사항입니다."),
    BOOK_NOT_FOUND(HttpStatus.NOT_FOUND, "존재하지 않는 책입니다."),
    NOT_FOUND_PETITION(HttpStatus.NOT_FOUND, "존재하지 않는 총학생회 청원입니다."),
    SECRET_PETITION(HttpStatus.FORBIDDEN, "비밀글입니다."),
    ITEM_NOT_FOUND(HttpStatus.NOT_FOUND, "존재하지 않는 물품 번호입니다."),
    INVALID_CATEGORY(HttpStatus.NOT_FOUND, "카테고리가 존재하지 않습니다."),
    OUT_OF_ITEM(HttpStatus.CONFLICT, "물품 예약 가능 수량이 부족합니다."),
    INAPPROPRIATE_RESERVATION_PERIOD(HttpStatus.BAD_REQUEST, "예약 가능 시간이 아닙니다."),
    INAPPROPRIATE_RENTAL_DAY(HttpStatus.BAD_REQUEST, "대여 및 반납 가능 날이 아닙니다."),
    INAPPROPRIATE_RENTAL_TIME(HttpStatus.BAD_REQUEST, "대여 및 반납 가능 시간이 아닙니다."),
    DUPLICATE_RESERVATION(HttpStatus.BAD_REQUEST, "동일한 사용자의 예약이 존재합니다."),
    RESERVATION_NOT_FOUND(HttpStatus.NOT_FOUND, "존재하지 않는 예약"),
    HAS_NOT_RESERVATION_AUTHORIZATION(HttpStatus.NOT_FOUND, "이 예약에 대한 삭제 권한이 없습니다."),
    LOST_PROPERTY_NOT_FOUND(HttpStatus.NOT_FOUND, "이 예약에 대한 삭제 권한이 없습니다."),
    BANNED_POST(HttpStatus.NOT_FOUND, "차단한 게시글입니다."),
    WRONG_PHONE_NUMBER(HttpStatus.BAD_REQUEST, "잘못된 전화번호 형식"),
    WRONG_RESERVATION_STATUS(HttpStatus.BAD_REQUEST, "잘못된 형식의 예약상태를 요청했습니다."),
    NOT_FOUND_CLUB(HttpStatus.NOT_FOUND, "존재하지 않는 동아리입니다."),
    TOKEN_NOT_FOUND(HttpStatus.NOT_FOUND, "존재하지 않는 토큰입니다."),
    KEYWORD_NOT_FOUND(HttpStatus.NOT_FOUND, "존재하지 않는 키워드입니다."),
    KEYWORD_ACCESS_DENIED(HttpStatus.FORBIDDEN, "이 키워드의 수정/삭제에 대한 권한이 없습니다."),
    MESSAGE_NOT_FOUND(HttpStatus.NOT_FOUND, "존재하지 않는 메시지입니다."),
    NOT_FOUND_LOG(HttpStatus.NOT_FOUND, "존재하지 않는 로그입니다."),
    FEATURE_DISABLED(HttpStatus.SERVICE_UNAVAILABLE, "현재 비활성화된 기능입니다."),
    FEATURE_FLAG_NOT_FOUND(HttpStatus.NOT_FOUND, "존재하지 않는 feature flag입니다."),
    DUPLICATE_FEATURE_FLAG_KEY(HttpStatus.BAD_REQUEST, "이미 존재하는 feature flag key입니다."),
    NOTICE_NOT_FOUND(HttpStatus.NOT_FOUND, "존재하지 않는 공지사항입니다."),
    TIMETABLE_NOT_FOUND(HttpStatus.NOT_FOUND, "존재하지 않는 시간표입니다."),
    TIMETABLE_ITEM_NOT_FOUND(HttpStatus.NOT_FOUND, "존재하지 않는 시간표 요소입니다."),
    SEMESTER_NOT_FOUND(HttpStatus.NOT_FOUND, "존재하지 않는 학기입니다."),
    DUPLICATE_TIMETABLE_NAME(HttpStatus.BAD_REQUEST, "같은 이름의 시간표가 존재합니다."),
    HAS_NOT_TIMETABLE_AUTHORIZATION(HttpStatus.FORBIDDEN, "해당 시간표에 접근할 권한이 없습니다."),
    INPUT_YEAR_AND_TERM(HttpStatus.BAD_REQUEST, "년도와 학기는 함께 입력해야합니다."),
    COURSE_NOT_FOUND(HttpStatus.BAD_REQUEST, "존재하지 않는 강의입니다."),
    COURSE_OFFERING_NOT_FOUND(HttpStatus.BAD_REQUEST, "존재하지 않는 개설 강의입니다."),
    NO_MATCH_SEMESTER(HttpStatus.BAD_REQUEST, "학기가 일치하지 않습니다."),
    NO_CUSTOM_ITEM_IN_TIMETABLE(HttpStatus.BAD_REQUEST, "해당 시간표에 속한 강의가 아닙니다."),
    NO_CUSTOM_ITEM(HttpStatus.BAD_REQUEST, "해당 요소는 커스텀 일정이 아닙니다."),
    NO_ITEM_IN_TIMETABLE(HttpStatus.BAD_REQUEST, "해당 시간표의 요소가 아닙니다."),
    NECESSARY_TIMETABLE_NAME(HttpStatus.BAD_REQUEST, "시간표 이름은 필수입니다."),
    NECESSARY_VISIBILITY(HttpStatus.BAD_REQUEST, "공개범위는 필수입니다."),
    NECESSARY_DAY_OF_WEEK(HttpStatus.BAD_REQUEST, "요일은 필수입니다."),
    NECESSARY_STARTTIME_AND_ENDTIME(HttpStatus.BAD_REQUEST, "시작시간과 종료시간은 필수입니다."),
    FASTER_THAN_ENDTIME(HttpStatus.BAD_REQUEST, "시작시간은 종료시간보다 빨라야합니다."),
    NECESSARY_CUSTOM_TITLE(HttpStatus.BAD_REQUEST, "커스텀 일정 제목은 필수입니다."),
    TIMETABLE_ITEM_TIME_CONFLICT(HttpStatus.CONFLICT, "시간표 요소의 시간이 중복입니다."),
    TIMETABLE_ITEM_TIME_REQUEST_CONFLICT(HttpStatus.CONFLICT, "동일한 시간의 시간표 요소를 추가할 수 없습니다."),
    TIMETABLE_ITEM_TIME_DB_CONFLICT(HttpStatus.CONFLICT, "동일한 시간의 시간표 요소가 존재합니다."),
    DUPLICATE_TIMETABLE_COURSE_ITEM(HttpStatus.CONFLICT, "이미 시간표에 추가된 개설 강의입니다."),
    PRIVATE_TIMETABLE(HttpStatus.FORBIDDEN, "비공개된 시간표입니다."),
    NOT_READABLE_TIMETABLE(HttpStatus.FORBIDDEN, "친구가 아닌 사용자의 시간표를 읽을 수 없습니다."),
    PRIMARY_TIMETABLE_NOT_FOUND(HttpStatus.NOT_FOUND, "대표 시간표가 존재하지 않습니다."),
    DUPLICATE_COURSE_OFFERING(HttpStatus.CONFLICT, "중복된 개설 강의입니다."),
    INVALID_DAY_OF_WEEK(HttpStatus.CONFLICT, "허용하지 않은 요일입니다."),
    MEETINGS_NOT_FOUND(HttpStatus.NOT_FOUND, "시간 정보가 존재하지 않습니다."),
    INVALID_DIRECTORY_SOURCE_CATEGORY(HttpStatus.BAD_REQUEST, "지원하지 않는 전화번호부 소스 카테고리입니다."),
    DIRECTORY_SOURCE_INVENTORY_NOT_FOUND(HttpStatus.BAD_GATEWAY, "전화번호부 소스 목록을 찾을 수 없습니다."),


    // Chat 관련 에러 코드 추가
    NOT_FOUND_CHATROOM(HttpStatus.NOT_FOUND, "존재하지 않는 채팅방입니다."),
    ALREADY_JOINED_CHATROOM(HttpStatus.CONFLICT, "이미 참여 중인 채팅방입니다."),
    CHATROOM_FULL(HttpStatus.FORBIDDEN, "채팅방의 최대 인원이 초과되었습니다."),
    NOT_CHATROOM_MEMBER(HttpStatus.FORBIDDEN, "채팅방 참여자가 아닙니다."),
    CHATROOM_CLOSED(HttpStatus.FORBIDDEN, "폐쇄된 채팅방입니다."),
    NOT_CHATROOM_OWNER(HttpStatus.FORBIDDEN, "채팅방 방장이 아닙니다."),
    NOT_FRIEND(HttpStatus.FORBIDDEN, "친구 관계가 아닙니다."),
    NOT_FOUND_FRIEND_REQUEST(HttpStatus.NOT_FOUND, "존재하지 않는 친구 요청입니다."),
    ALREADY_FRIEND_OR_REQUESTED(HttpStatus.CONFLICT, "이미 친구이거나 요청 대기 중입니다."),
    NOT_SELF_FRIEND_REQUEST(HttpStatus.BAD_REQUEST, "자기 자신에게 친구 요청을 보낼 수 없습니다."),
    NOT_SELF_BLOCK(HttpStatus.BAD_REQUEST, "자기 자신을 차단할 수 없습니다."),
    NOT_SELF_CHAT(HttpStatus.BAD_REQUEST, "자기 자신과는 채팅방을 만들 수 없습니다."),
    HAS_NOT_FRIEND_AUTHORIZATION(HttpStatus.FORBIDDEN, "친구 관련 작업을 수행할 권한이 없습니다."),
    NOT_ADMIN(HttpStatus.FORBIDDEN, "관리자 권한이 없습니다."),
    INVALID_OFFICIAL_CHAT_TARGET(HttpStatus.BAD_REQUEST, "운영자 채팅은 일반 학생하고만 가능합니다."),
    INVALID_INPUT(HttpStatus.BAD_REQUEST, "잘못된 입력값입니다."),
    INVALID_NICKNAME_KEYWORD(HttpStatus.BAD_REQUEST, "사용할 수 없는 단어(알림, 운영진 등)가 포함된 닉네임입니다."),
    ;


    private final HttpStatus status;
    private final String message;
}
