{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sentry",
    "module": "sentry",
    "version": "8.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "sentry-8.1.0.jar",
          "url": "sentry-8.1.0.jar",
          "size": 960518,
          "sha512": "ccbc4e9e8ce93ead2eab9db7e97a39b4c7f88d6d96394e14678b27da1e80604a5b8b1d2ab9d6268b72347a217aef4f373fd40c3bdaa956266f78893721d14e7a",
          "sha256": "93231c84dceca324472d0df8319419e3b5ed436695a9ad5a4bfc3a442b71cd3e",
          "sha1": "621b8f833db89527b4aff2ccf047dbe310e87bfb",
          "md5": "f125b73925f491e14b29eec6c88f77cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "sentry-8.1.0.jar",
          "url": "sentry-8.1.0.jar",
          "size": 960518,
          "sha512": "ccbc4e9e8ce93ead2eab9db7e97a39b4c7f88d6d96394e14678b27da1e80604a5b8b1d2ab9d6268b72347a217aef4f373fd40c3bdaa956266f78893721d14e7a",
          "sha256": "93231c84dceca324472d0df8319419e3b5ed436695a9ad5a4bfc3a442b71cd3e",
          "sha1": "621b8f833db89527b4aff2ccf047dbe310e87bfb",
          "md5": "f125b73925f491e14b29eec6c88f77cf"
        }
      ]
    }
  ]
}
