{
  "formatVersion": "1.1",
  "component": {
    "group": "io.opentelemetry",
    "module": "opentelemetry-sdk-extension-autoconfigure",
    "version": "1.31.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-extension-autoconfigure-spi",
          "version": {
            "requires": "1.31.0"
          }
        }
      ],
      "files": [
        {
          "name": "opentelemetry-sdk-extension-autoconfigure-1.31.0.jar",
          "url": "opentelemetry-sdk-extension-autoconfigure-1.31.0.jar",
          "size": 40525,
          "sha512": "d4b80633afcde0079451655d6c015be6d86a8387be372292d0632a6cc72ba3ceacceafbdd41edd21a0d66fe493b027597a438a13e5b073dc278dbb013f67aafe",
          "sha256": "819a6c5824b01b6f2d2abe590a917a892ee91380778ea4b4673d80f35d9cd902",
          "sha1": "178efb4a6102afa581307038f609324ed4418025",
          "md5": "bbc29137ec5b1c3e2dd6b7503bff243e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api-events",
          "version": {
            "requires": "1.31.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.31.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-extension-autoconfigure-spi",
          "version": {
            "requires": "1.31.0"
          }
        }
      ],
      "files": [
        {
          "name": "opentelemetry-sdk-extension-autoconfigure-1.31.0.jar",
          "url": "opentelemetry-sdk-extension-autoconfigure-1.31.0.jar",
          "size": 40525,
          "sha512": "d4b80633afcde0079451655d6c015be6d86a8387be372292d0632a6cc72ba3ceacceafbdd41edd21a0d66fe493b027597a438a13e5b073dc278dbb013f67aafe",
          "sha256": "819a6c5824b01b6f2d2abe590a917a892ee91380778ea4b4673d80f35d9cd902",
          "sha1": "178efb4a6102afa581307038f609324ed4418025",
          "md5": "bbc29137ec5b1c3e2dd6b7503bff243e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opentelemetry-sdk-extension-autoconfigure-1.31.0-javadoc.jar",
          "url": "opentelemetry-sdk-extension-autoconfigure-1.31.0-javadoc.jar",
          "size": 91140,
          "sha512": "d2bd79495eaadf96e2808c29e02985244ae52d2ca8288b599bf4919ff44ae10a08804d3e2d4a77e718ac06f569ea88fb69c04d8310adf34e16ded317655bd9b5",
          "sha256": "1a7a2d4940931a771ede5d758c054fe3d6b090eede760327ae036b4380a60626",
          "sha1": "91ada7209750158a5b6b97fae8597f6221c7e5d0",
          "md5": "1568f7ef6268b377b914c6ad0b1065b1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opentelemetry-sdk-extension-autoconfigure-1.31.0-sources.jar",
          "url": "opentelemetry-sdk-extension-autoconfigure-1.31.0-sources.jar",
          "size": 21492,
          "sha512": "b5c6e47bcfbb929b6252d12ceb079f427df5b267315f71889899755d69405b5a0fc3f44164a866087ba414857176fa1250651ba92d3e8d8b4e26beb900ee39f4",
          "sha256": "7fe4cf179abd0854bb3292f4a833a875048a73297a1e3b6d2a003abef277762f",
          "sha1": "f82431418c73edc8018820d8b308074a1ee0968a",
          "md5": "dcffb24e870e480bfcccdb17a7eb2271"
        }
      ]
    }
  ]
}
