{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-security",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-config",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-security-3.2.1.jar",
          "url": "spring-boot-starter-security-3.2.1.jar",
          "size": 4740,
          "sha512": "e299f8ff8ead3b1720361caac820cec7d016f57cb330d67aff82915c340e728838fc3ffca3b0ef4eb03a31efc2a2fb42219b8679209eba620e1f9214f112bf29",
          "sha256": "4a1612ab374bface680c0131948dde82f3ced77d39fe1a482bc6ded86114f664",
          "sha1": "86b7029d55fe7947ea7a93b4b1b38ff80bd045f8",
          "md5": "4f0a8c59f45a9853c26a7902409c2672"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-config",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "6.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-security-3.2.1.jar",
          "url": "spring-boot-starter-security-3.2.1.jar",
          "size": 4740,
          "sha512": "e299f8ff8ead3b1720361caac820cec7d016f57cb330d67aff82915c340e728838fc3ffca3b0ef4eb03a31efc2a2fb42219b8679209eba620e1f9214f112bf29",
          "sha256": "4a1612ab374bface680c0131948dde82f3ced77d39fe1a482bc6ded86114f664",
          "sha1": "86b7029d55fe7947ea7a93b4b1b38ff80bd045f8",
          "md5": "4f0a8c59f45a9853c26a7902409c2672"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-security-3.2.1.jar",
          "url": "spring-boot-starter-security-3.2.1.jar",
          "size": 4740,
          "sha512": "e299f8ff8ead3b1720361caac820cec7d016f57cb330d67aff82915c340e728838fc3ffca3b0ef4eb03a31efc2a2fb42219b8679209eba620e1f9214f112bf29",
          "sha256": "4a1612ab374bface680c0131948dde82f3ced77d39fe1a482bc6ded86114f664",
          "sha1": "86b7029d55fe7947ea7a93b4b1b38ff80bd045f8",
          "md5": "4f0a8c59f45a9853c26a7902409c2672"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-security-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-security-3.2.1.jar",
          "url": "spring-boot-starter-security-3.2.1.jar",
          "size": 4740,
          "sha512": "e299f8ff8ead3b1720361caac820cec7d016f57cb330d67aff82915c340e728838fc3ffca3b0ef4eb03a31efc2a2fb42219b8679209eba620e1f9214f112bf29",
          "sha256": "4a1612ab374bface680c0131948dde82f3ced77d39fe1a482bc6ded86114f664",
          "sha1": "86b7029d55fe7947ea7a93b4b1b38ff80bd045f8",
          "md5": "4f0a8c59f45a9853c26a7902409c2672"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-security-maven-optional",
          "version": "3.2.1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-security-3.2.1-javadoc.jar",
          "url": "spring-boot-starter-security-3.2.1-javadoc.jar",
          "size": 4743,
          "sha512": "cff7dd9b7b3ad6cf0c14e43c1866378a79fa2aa5be0ade16c3a1c05a834a1d65324eaf3f0148ed9cb1b0e558c255d70db506ec00ea31e3df2a8871470a60b45c",
          "sha256": "434bf59b1b4ed35837b535976dadb026b881188405d75a237105dc5a37f73be3",
          "sha1": "cd70a2a766ea614a584d3fefea991f42677693c9",
          "md5": "1f281443d6fec0ead3da3501ecdfbc8f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-security-3.2.1-sources.jar",
          "url": "spring-boot-starter-security-3.2.1-sources.jar",
          "size": 4742,
          "sha512": "4d6ab1711d4930cfc6faec908ec171dae3ca939d79c74c0683db2c567013b80a67a25659cbc72cf7b2e41036259e02f5647926caa572ca3879d06ea42bb073d4",
          "sha256": "e3254e19d41b65646536399fce81bea25ea8bdc7a6a65d6c96535c62cc351460",
          "sha1": "a817a3f01d3aa35b9d3145924bf434c9777c437c",
          "md5": "f3d7a73d24465a97d67747ba80a41935"
        }
      ]
    }
  ]
}
