{
  "formatVersion": "1.1",
  "component": {
    "group": "io.sentry",
    "module": "sentry-spring-jakarta",
    "version": "8.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.sentry",
          "module": "sentry",
          "version": {
            "requires": "8.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sentry-spring-jakarta-8.1.0.jar",
          "url": "sentry-spring-jakarta-8.1.0.jar",
          "size": 98945,
          "sha512": "b2cd770b70956cd84909517b40dca3a606da69b40c7dc4fd2126f1ad3b4a7a5fe977d2afc56a56481aefe409eaaeb4744b5270ae5b5a3554436eab55a0bc4827",
          "sha256": "0662e643aa1ed02a85305b09e7243150dea65dcde9220e88aa082caf1a384e1a",
          "sha1": "73ed0dac40c656a435c3a1c5315139ad43abff8f",
          "md5": "9577074a26f926b8a27e3e8b8176479b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.sentry",
          "module": "sentry",
          "version": {
            "requires": "8.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "sentry-spring-jakarta-8.1.0.jar",
          "url": "sentry-spring-jakarta-8.1.0.jar",
          "size": 98945,
          "sha512": "b2cd770b70956cd84909517b40dca3a606da69b40c7dc4fd2126f1ad3b4a7a5fe977d2afc56a56481aefe409eaaeb4744b5270ae5b5a3554436eab55a0bc4827",
          "sha256": "0662e643aa1ed02a85305b09e7243150dea65dcde9220e88aa082caf1a384e1a",
          "sha1": "73ed0dac40c656a435c3a1c5315139ad43abff8f",
          "md5": "9577074a26f926b8a27e3e8b8176479b"
        }
      ]
    }
  ]
}
