{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-test",
    "version": "6.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-test-6.2.1.jar",
          "url": "spring-security-test-6.2.1.jar",
          "size": 132163,
          "sha512": "b53d1793ac42ad1e100edee662627e59ef6473d46e3ceda4851759d70a89806d2c062e041087115e10a00c6272fe85644ac01b8dbd75f9f71a857bc09bfbf7df",
          "sha256": "5da7806f5b4b9eb5d0964100f1b9ace64355f5baa4e10fc78f7bddf93741e381",
          "sha1": "5e88b6a8c51a56dfe2756ac7143f04c07553de03",
          "md5": "a5be067b0c065b5718143d1c78e4ba19"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-test-6.2.1.jar",
          "url": "spring-security-test-6.2.1.jar",
          "size": 132163,
          "sha512": "b53d1793ac42ad1e100edee662627e59ef6473d46e3ceda4851759d70a89806d2c062e041087115e10a00c6272fe85644ac01b8dbd75f9f71a857bc09bfbf7df",
          "sha256": "5da7806f5b4b9eb5d0964100f1b9ace64355f5baa4e10fc78f7bddf93741e381",
          "sha1": "5e88b6a8c51a56dfe2756ac7143f04c07553de03",
          "md5": "a5be067b0c065b5718143d1c78e4ba19"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-test-6.2.1-javadoc.jar",
          "url": "spring-security-test-6.2.1-javadoc.jar",
          "size": 233726,
          "sha512": "00cd33cc023b3bbd5d43bb6573cbb114adbba3c645ef89342911297c6942e306798e996530cc1c193b4bac0cc69fc86f33297934c4adf76bd054fa8417b7c33d",
          "sha256": "032974a8a4fe2e054b45e39480e44e243bc629f51af82f849c94e1c89f45aa2c",
          "sha1": "1f4e2fcfaba2d3a0f8578c0adccff75fc5155a29",
          "md5": "6c8de1b568a0df9a92a119a0790c83b2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-test-6.2.1-sources.jar",
          "url": "spring-security-test-6.2.1-sources.jar",
          "size": 56428,
          "sha512": "6ca4baf6279a9fe4c7aa539a7c292e898a522bb52a2e1f53595b2004c99122d9a7030274a131fcc243e8b9792003e7621ef7db51ba2c1a1b8dc61b8cc365eb7a",
          "sha256": "86f2142e44ac75563ca86bf8c586c0f0d483725a6c6970f77296f7781d898a22",
          "sha1": "0c00952a4ac68d243a8da6d076b540e3e75a9e24",
          "md5": "54d154f783c0095838fde1bab9613303"
        }
      ]
    }
  ]
}
